# 本番環境への自動デプロイワークフロー
name: Deploy Next.js site to Production

on:
  # mainブランチにプッシュされた時に実行
  push:
    branches: ["main"]
  # Actionsタブから手動で実行することも可能
  workflow_dispatch:

# GITHUB_TOKENのパーミッションを設定
permissions:
  contents: read
  id-token: write
  actions: read
  deployments: write

# 同時デプロイを1つに制限
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # ビルドジョブ
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      
      - name: Install dependencies
        run: npm install
      
      - name: Build with Next.js
        run: npm run build
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: ./out

  # 本番環境デプロイジョブ（tkenta-git.github.io）
  deploy-prod:
    environment:
      name: github-pages
      url: https://kenta-tanaka.com
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: ./out
      
      - name: Checkout production repository
        uses: actions/checkout@v4
        with:
          repository: tkenta-git/tkenta-git.github.io
          token: ${{ secrets.DEPLOY_TOKEN }}
          path: production-repo
      
      - name: Copy built files to production
        run: |
          cp -r out/* production-repo/
          cd production-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Auto-deploy from kenta-portfolio-dev: ${{ github.sha }}"
          git push origin main